<?php

namespace AppBundle\Repository;

/**
 * ReceptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceptRepository extends \Doctrine\ORM\EntityRepository
{
	/*
    * получаем рецпт
    */
    public function getProducts($id)
    {
         $qb = $this->createQueryBuilder('p')
                    ->select('p', 'product', 'product.name', 'product.cost', 'product.id')
                    ->join('p.products', 'product')
                    ->where('product.id = :id')
                    ->setParameter('id', $id);

        return $qb->getQuery()->getResult();
    }
}
